### ISSUE TITLE
The Chrome Web Store Link 404s

### ISSUE THREAD

**Issue by atomdmac** [petrenkoVitaliy/formik-devtools#13]
Not sure if this is because of an issue with the web store or if the extension was purposely removed.

**Link:** https://chrome.google.com/webstore/detail/dadeefbkfcpaeacnafgceahcpjlfmmjj

![image](https://user-images.githubusercontent.com/1461736/181820443-f6be98e5-a3cd-49b3-9059-106da996c171.png)

**Comment by petrenkoVitaliy** [comment]
Hello, thanks for ticket. Will be fixed ASAP

**Comment by petrenkoVitaliy** [comment]
Fixed
