### ISSUE TITLE
Chrome Web Store version mismatches latest release version here on GitHub 

### ISSUE THREAD

**Issue by tcschiller** [petrenkoVitaliy/formik-devtools#15]
Our engineering team noticed a version bump for the Formik Devtools extension in the Chrome Web Store (to 0.3.1). But, the latest release cut here on GitHub is 0.3.0.

As you can imagine, this caused a flurry of speculation and activity on our end as we tried to discover the cause of the version bump mismatch. Can you shed any light on the matter? What changed, exactly? And why hasn't GitHub been updated in concert? Is this extension still actively maintained, or should we consider alternatives?

We appreciate your time and attention to this matter!

**Comment by petrenkoVitaliy** [comment]
Hi, thanks for noticing this 👍 , the last version only had package versions' updates and manifest.json (extension config file) updates, this was forced by the new Google Web Store policy. In general, the unused permission is simply deleted there.
Looks like I just forgot to commit changes, maybe there was an air alarm that distracted me 😅 
This extension will be supported for now, but new features and active maintenance are planned for the future.

Thanks for your question, I hope this extension really helps you in your work
