### ISSUE TITLE
Can I use it with nextjs?

### ISSUE THREAD

**Issue by phaethon5882** [petrenkoVitaliy/formik-devtools#16]
Thanks for making such a great extension.
I am developing using next.js and formik. 
However, when calling 'withFormikDevtools' following error occurrs.
```txt
error - ReferenceError: window is not defined
```

I Think, The extendedWindow assignment statement seems to be the problem.
```javascript
var extendedWindow = window;
var FormikDevtools = function () {
```
So I changed it to do client side rendering with next/dynamic.

I tried to make a pull request, but it was rejected.
so i forked this repository, and fix it.
> https://github.com/phaethon5882/formik-devtools

**Comment by petrenkoVitaliy** [comment]
Hi, thanks for pointing this. I've checked your changes in fork and yes, this looks like a solution to the problem
`const extendedWindow: ExtendedWindow | null = typeof window === 'undefined' ? null : window;` + optional chaining.
Which PR was rejected? I haven't seen any.

**Comment by petrenkoVitaliy** [comment]
Fixed with last [commit](https://github.com/petrenkoVitaliy/formik-devtools/commit/de51031d1310a82371e1d84179fcb991d06177f9)
New version of the package [formik-devtools-extension (0.1.8)](https://www.npmjs.com/package/formik-devtools-extension) was published 
Thank you
