### ISSUE TITLE
Использование с react hook

### ISSUE THREAD

**Issue by Hydrock** [petrenkoVitaliy/formik-devtools#3]
Привет. Можно как то с хуками использовать. Когда формик используктся через хуки. Если да - мог бы ты написать README? 
Если нет - кажется, эта функция очень нужна

**Comment by Hydrock** [comment]
PR https://github.com/petrenkoVitaliy/formik-devtools/pull/4

**Comment by petrenkoVitaliy** [comment]
Привет. Отличное замечание) Спасибо, сейчас добавим :+1:
