### ISSUE TITLE
Name length of tab

### ISSUE THREAD

**Issue by stephenway** [petrenkoVitaliy/formik-devtools#7]
Hello, I recently integrated this into a project I'm working on, and I think it's fantastic. Thank you for building this tool! I would like to make a suggestion and can provide a PR if acceptable, but given the number of tabs between what comes with devtools and the react devtools tabs, I think this extension could reduce the panel tab name from "Formik Devtools" to simply "Formik".

Let me know if this seems like a reasonable suggestion and I can get on a PR for this change. Thanks!

**Comment by petrenkoVitaliy** [comment]
Hello, Im very happy to to read this feedback! :smile: 
I think this is a good idea, so I've already updated title from "Formik Devtools" to "Formik".
Thank you)
